# Generated by Django 4.2.7 on 2024-01-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0002_alter_scrap_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='status',
            field=models.CharField(choices=[('Buy now', 'Buy now'), ('Sold out', 'Sold out')], default='Buy now', max_length=100),
        ),
    ]
