# Generated by Django 4.2.7 on 2024-01-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0003_alter_scrap_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wishlists',
            field=models.ManyToManyField(null=True, related_name='cart_item', to='scrapapp.wishlist'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='scrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraps', to='scrapapp.scrap'),
        ),
    ]
