# Generated by Django 4.2.7 on 2024-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0004_wishlist_wishlists_alter_wishlist_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wishlists',
            field=models.ManyToManyField(null=True, related_name='cart_item', to='scrapapp.userprofile'),
        ),
    ]
