# Generated by Django 4.2.7 on 2024-01-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0005_userprofile_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wishlists',
            field=models.ManyToManyField(blank=True, related_name='wishlisted_by', to='scrapapp.scrap'),
        ),
    ]
